#include QMK_KEYBOARD_H

// Module headers.

#include "core_keymap.h"
#include "custom_keys.h"

// Keymap.

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [LAYER_BASE] = LAYOUT_ferris_sweep(
      CORE_LBASE_FOT, CORE_LBASE_T,    CORE_LBASE_FIT, CORE_RBASE_FIT, CORE_RBASE_T, CORE_RBASE_FOT,
      CORE_LBASE_FOM, CORE_LBASE_M,    CORE_LBASE_FIM, CORE_RBASE_FIM, CORE_RBASE_M, CORE_RBASE_FOM,
      CORE_LBASE_FOB, CORE_LBASE_B,    CORE_LBASE_FIB, CORE_RBASE_FIB, CORE_RBASE_B, CORE_RBASE_FOB,
                      CORE_LBASE_FOTH, CORE_LBASE_TH,  CORE_RBASE_TH,  CORE_RBASE_FOTH
  ),
  [LAYER_LEXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LEXT_T,    CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_LEXT_M,    CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_LEXT_B,    CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                      CORE_LEXT_FOTH, CORE_LEXT_TH,   CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_REXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LFILL_T,    CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_REXT_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_LFILL_M,    CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_REXT_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_LFILL_B,    CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_REXT_B, CORE_RFILL_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_REXT_TH,   CORE_REXT_FOTH
  ),
  [LAYER_LSYM] = LAYOUT_ferris_sweep(
      CORE_LSYM_FOT, CORE_LSYM_T,     CORE_LSYM_FIT, CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_LSYM_FOM, CORE_LSYM_M,     CORE_LSYM_FIM, CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_LSYM_FOB, CORE_LSYM_B,     CORE_LSYM_FIB, CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                     CORE_LFILL_FOTH, CORE_LFILL_TH, CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_LSYM_EXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LSYM_EXT_T, CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_LSYM_EXT_M, CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_LSYM_EXT_B, CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_RSYM] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LFILL_T,    CORE_LFILL_FIT, CORE_RSYM_FIT, CORE_RSYM_T, CORE_RSYM_FOT,
      CORE_LFILL_FOM, CORE_LFILL_M,    CORE_LFILL_FIM, CORE_RSYM_FIM, CORE_RSYM_M, CORE_RSYM_FOM,
      CORE_LFILL_FOB, CORE_LFILL_B,    CORE_LFILL_FIB, CORE_RSYM_FIB, CORE_RSYM_B, CORE_RSYM_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH, CORE_RFILL_FOTH
  ),
  [LAYER_RSYM_EXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LFILL_T,    CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_RSYM_EXT_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_LFILL_M,    CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_RSYM_EXT_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_LFILL_B,    CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_RSYM_EXT_B, CORE_RFILL_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_NUM] = LAYOUT_ferris_sweep(
      CORE_NUM_FOT, CORE_NUM_T,      CORE_NUM_FIT,  CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_NUM_FOM, CORE_NUM_M,      CORE_NUM_FIM,  CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_NUM_FOB, CORE_NUM_B,      CORE_NUM_FIB,  CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                    CORE_LFILL_FOTH, CORE_LFILL_TH, CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_NUM_EXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_NUM_EXT_T,  CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_NUM_EXT_M,  CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_NUM_EXT_B,  CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_NAV] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LFILL_T,    CORE_LFILL_FIT, CORE_NAV_FIT,  CORE_NAV_T, CORE_NAV_FOT,
      CORE_LFILL_FOM, CORE_LFILL_M,    CORE_LFILL_FIM, CORE_NAV_FIM,  CORE_NAV_M, CORE_NAV_FOM,
      CORE_LFILL_FOB, CORE_LFILL_B,    CORE_LFILL_FIB, CORE_NAV_FIB,  CORE_NAV_B, CORE_NAV_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH, CORE_RFILL_FOTH
  ),
  [LAYER_NAV_EXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LFILL_T,    CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_NAV_EXT_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_LFILL_M,    CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_NAV_EXT_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_LFILL_B,    CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_NAV_EXT_B, CORE_RFILL_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_FUNC] = LAYOUT_ferris_sweep(
      CORE_FUNC_FOT, CORE_FUNC_T,     CORE_FUNC_FIT, CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_FUNC_FOM, CORE_FUNC_M,     CORE_FUNC_FIM, CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_FUNC_FOB, CORE_FUNC_B,     CORE_FUNC_FIB, CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                     CORE_LFILL_FOTH, CORE_LFILL_TH, CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_FUNC_EXT] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_FUNC_EXT_T, CORE_LFILL_FIT, CORE_RFILL_FIT, CORE_RFILL_T, CORE_RFILL_FOT,
      CORE_LFILL_FOM, CORE_FUNC_EXT_M, CORE_LFILL_FIM, CORE_RFILL_FIM, CORE_RFILL_M, CORE_RFILL_FOM,
      CORE_LFILL_FOB, CORE_FUNC_EXT_B, CORE_LFILL_FIB, CORE_RFILL_FIB, CORE_RFILL_B, CORE_RFILL_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH,  CORE_RFILL_FOTH
  ),
  [LAYER_CTLS] = LAYOUT_ferris_sweep(
      CORE_LFILL_FOT, CORE_LFILL_T,    CORE_LFILL_FIT, CORE_CTLS_FIT, CORE_CTLS_T, CORE_CTLS_FOT,
      CORE_LFILL_FOM, CORE_LFILL_M,    CORE_LFILL_FIM, CORE_CTLS_FIM, CORE_CTLS_M, CORE_CTLS_FOM,
      CORE_LFILL_FOB, CORE_LFILL_B,    CORE_LFILL_FIB, CORE_CTLS_FIB, CORE_CTLS_B, CORE_CTLS_FOB,
                      CORE_LFILL_FOTH, CORE_LFILL_TH,  CORE_RFILL_TH, CORE_RFILL_FOTH
  )
};
